#!/bin/sh

if [ -z "$1" ]; then
	echo "Usage: $(basename $0) <ruby-path> >>~/.profile" >&2
	echo "       eval \$($(basename $0) <ruby-path>)" >&2
	exit 1
fi

if [ -x "$1/ruby" ]; then
	echo "export PATH=\"$1:\$PATH\""
elif [ -x "$1/bin/ruby" ]; then
	echo "export PATH=\"$1/bin:\$PATH\""
elif [ -x "/opt/$1/bin/ruby" ]; then
	echo "export PATH=\"/opt/$1/bin:\$PATH\""
elif [ -x "/opt/ruby-$1/bin/ruby" ]; then
	echo "export PATH=\"/opt/ruby-$1/bin:\$PATH\""
else
	echo "[pick-ruby] no ruby found in $1" >&2
fi
